### ISSUE TITLE
Executable files on the encrypted drive?

### ISSUE THREAD

**Issue by RCheesley** [KenMacD/wdpassport-utils#10]
I'm struggling with having executable files on the encrypted drive - it doesn't seem that you're able to set any of the files a+x either in the GUI or at command line.

The context for this being that some of the apps I use like PHPStorm require scripts within their settings directory to be executed, so when I move the settings over to the drive they don't launch.

Any ideas? Can anyone else replicate this?

**Comment by tqz** [comment]
What filesystem do you use on the unlocked wd?
Den 28 jun 2015 1:07 em skrev "Ruth Cheesley" <notifications@github.com>:

**Comment by RCheesley** [comment]
Thanks for the reply.  Here's the output from fdisk - I haven't made any changes at all to the format of the directory, it's just "as it comes".

Disk /dev/sdc: 1000.2 GB, 1000170586112 bytes
255 heads, 63 sectors/track, 121597 cylinders, total 1953458176 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x65b14d59

   Device Boot      Start         End      Blocks   Id  System
/dev/sdc1            2048  1953458175   976728064    7  HPFS/NTFS/exFAT

**Comment by tqz** [comment]
Without remounting the drive, you will have to execute the shell or 
other interpreter first, not the script directly.

File permissions will not work as expected with NTFS the way you are 
mounting it now:

$ ls -l script
-rw------- 1 woody woody 21 jun 28 13:57 script
$ chmod u+x script
$ ls -l script
-rw------- 1 woody woody 21 jun 28 13:57 script
$ chmod a+x script
$ ls -l script
-rw------- 1 woody woody 21 jun 28 13:57 script

So executing directly will not work:
$ ./script
bash: ./script: Permission denied

Start interpreter first (shell, php, python, whatever) :
$ sh script
works

$ cat script
#!/bin/sh
echo works

If this is not possible for some reason, you can remount the filesystem 
with executable permissions enabled.

Add "permissions" as a mount option.

Example: 
http://superuser.com/questions/638326/chmod-777-no-effects-on-linux-mint

**Comment by RCheesley** [comment]
I don't think that will work, as it's not me running the executable it's activated by PHPStorm during startup.  Presume I can try to mount the drive with executable permissions enabled but when I tried mounting before it wouldn't work (I ended up using partprobe to get it to mount) - so might need to tinker a bit I guess.  Thanks for the feedback though, really appreciate it.

**Comment by RCheesley** [comment]
I've tried a multitude of ways to get the drive to mount with executable permissions but I simply don't seem to be able to get the drive to mount without using partprobe.  Entirely possible there's something I don't know.

I tried using the solution proposed here: http://superuser.com/questions/638326/chmod-777-no-effects-on-linux-mint

Also tried this proposed solution: http://askubuntu.com/questions/83461/automatically-mount-ntfs-drive-when-i-login

Whenever I try to mount /dev/sdc1 I get the following:

    rcheesley@Puddle:~/wdpassport-utils-master$ sudo mount -t ntfs -o rw,nosuid,nodev,relatime,permissions /dev/sdc1 /media/rcheesley/My\ Passport
ntfs-3g: Failed to access volume '/dev/sdc1': No such file or directory

**Comment by tqz** [comment]
Since you need to unlock it first, there will be some tweaking.

When you have unlocked & mounted the drive the way you do now, check 
where it is mounted, and remount it:

If it is mounted on /dev/sdc1 (check with *mount* command), do this:

|sudo mount -t ntfs -o*remount,*rw,nosuid,nodev,relatime,permissions /dev/sdc1 /media/rcheesley/My\ Passport
|


//Daniel

**Comment by RCheesley** [comment]
I tried that, but I get the following - note this is immediately after mounting via portprobe with no apps running:

    rcheesley@Puddle:~/wdpassport-utils-master$ sudo mount -t ntfs -o*remount,*rw,nosuid,nodev,relatime,permissions /dev/sdc1 /media/rcheesley/My\ Passport
    Mount is denied because the NTFS volume is already exclusively opened.
    The volume may be already mounted, or another software may use it which
could be identified for example by the help of the 'fuser' command.

**Comment by tqz** [comment]
What is the "mount" output of your ntfs drive?

Also, run fuser as suggested. For instance: sudo fuser -v /dev/sdc1

**Comment by itay-grudev** [comment]
I don't think this issue relates to a bug with `wdpassport-utils` so I recommend that you close it.

**Comment by KenMacD** [comment]
@RCheesley sorry, as @itay-grudev says this is unrelated to the actual unlocking of the drive, and instead related to your choice of filesystems. Please try on more standard Linux support options.
