### ISSUE TITLE
Can not find device with dmesg

### ISSUE THREAD

**Issue by MTRNord** [KenMacD/wdpassport-utils#12]
I cant find the device number with dmesg. The unlocker CD is mounted automatic but I dont see the needed Partition. Are there other ways to find it?

**Comment by KenMacD** [comment]
Sorry, I don't have a drive with me right at the moment. I think newer kernels just give them a /dev/sd[abc...] instead of /dev/sg. Try `dmesg | grep -i scsi` and see what comes up.

**Comment by MTRNord** [comment]
I will close it now. Readme has it in #13 as info.
