### ISSUE TITLE
Command to turn it off

### ISSUE THREAD

**Issue by killua99** [KenMacD/wdpassport-utils#15]
There's a possibility to make a command to turn off the device itself like the Util for Windows and Mac that can disconnect (turning off) the device?

**Comment by DanLukes** [comment]
On 29.3.2016 13:57, luigi wrote:
> There's a possibility to make a command to turn off the device itself like the Util for Windows and Mac that can disconnect (turning off) the device?

It's not device specific action. You can just power off the particular 
USB plug the WD disk is connected to.

The required command need not to be send to WD disk, but to the USB hub 
powering the plug. So it has nothing to do with the connected device.

Use the OS utility suitable to switch USB power on and off.

Dan

**Comment by killua99** [comment]
Alright I get it, I thought could be something like the Utility execute a series of instructions to set the device in sleep mode, then umont the device and later turn the hub power off.

But maybe I could work that in a different way.

Thanks for the clarification.

**Comment by KenMacD** [comment]
@killua99 Did you mean something like:

    udiskctl unmount -b /dev/sdb
    udiskctl power-off -b /dev/sdb

or the older:

    udisks --unmount /dev/sdb
    udisks --detach /dev/sdb

That should get it to the slow-flashing 'disconnected' state.

**Comment by Zibri** [comment]
`sg_raw $dev 1b 00 00 00 00 00  puts the drive in standby`
`sg_raw $dev 1b 00 00 00 01 00  turns it back on.`
