### ISSUE TITLE
"./cookpw.py <password> >password.bin" gives error

### ISSUE THREAD

**Issue by Nuc1eoN** [KenMacD/wdpassport-utils#2]
Hi and thanks for this excellent work!

However when I execute "./cookpw.py <password> >password.bin" I get the following error:

     Traceback (most recent call last):
      File "./cookpw.py", line 25, in <module>
         main(sys.argv[1])
      File "./cookpw.py", line 17, in main
         header = header.decode("hex")
     AttributeError: 'str' object has no attribute 'decode'

**Comment by KenMacD** [comment]
Hi @Nuc1eoN, thanks for the report. You'll only see this on Python 3. Try: `python2 cookpw.py` and it should work.

This code should probably be updated to work in both Python 2 and Python 3, so I'll leave this issue open until I make that change.

**Comment by Nuc1eoN** [comment]
Thanks, this seems to work. However I am unable to mount my device in the next steps:
````
# sg_raw -s 40 -i password.bin /dev/sg6 c1 e1 00 00 00 00 00 00 28 00
SCSI Status: Good
````

````
# mount /dev/sg6 /media/wdpass/
mount:  /dev/sg6 is not a block device
````

Did I do something wrong or is this a bug?

**Comment by KenMacD** [comment]
I believe you would most commonly see this if the drive did not actually unlock.

Is the drive working in either Windows or OSX? iirc they also have some type of locking if you try to many wrong passwords, but I think that's just until they're unplugged and plugged in again.

**Comment by Nuc1eoN** [comment]
No, actually it works on Windows 7 and the password should be correct. But for convinience I can try to reproduce it again.

**Comment by KenMacD** [comment]
@Nuc1eoN can you try the same commands from #8. I'd like to see if the drive thinks it's unlocked or not.

**Comment by KenMacD** [comment]
Also once the drive is unlocked, or should be unlocked, try `sudo partprobe`, then check/paste the end of `dmesg`.

**Comment by KenMacD** [comment]
Oh, I think I know what's up with this and #8, although I don't have a drive here to test it. Iirc you don't actually mount the scsi device. You should instead see new device once you either unlock the drive, or run `partprobe`. That's what you mount.

**Comment by Nuc1eoN** [comment]
Yeah it works thanks! :)
