### ISSUE TITLE
Unable to detect drive

### ISSUE THREAD

**Issue by dushyantbangal** [KenMacD/wdpassport-utils#22]
I'm using ubuntu 16.04, kernel 4.4.0-119-generic, python 2.7

I'm trying to use `gui.py`, but I don't think its detecting the drive.
I'm getting the following in the status text box:

```
Calling external cookpw-script...
Sending SCSI commands to encrypt/unlock the drive...
Secure Harddrive identified at /dev/type
Failure while sending SCSI encrypt command -> Check if harddrive is connected properly! (Maybe /dev/type does not exist)
```

My drive is at `/dev/sdb`, is the program thinking its at `/dev/type`?

**Comment by KenMacD** [comment]
What output do you get when you try:

`/bin/dmesg | grep sg | grep "type 13" | awk '{print $8}'`

And if that's `type` try just:

`/bin/dmesg | grep sg | grep "type 13" `

As a more immediate workaround you can use the command-line version:

     python cookpy.py PASSWORD >/tmp/password.bin
    sudo sg_raw -s 40 -i /tmp/password.bin /dev/sdb c1 e1 00 00 00 00 00 00 28 00

(I know in zsh the space at the start of a command keeps it from showing up in `history`, you might need to `unset HISTFILE` to do the same in bash.)
