### ISSUE TITLE
No execution from command sudo ./wd-security.py

### ISSUE THREAD

**Issue by ShanChathusanda93** [KenMacD/wdpassport-utils#24]
I am using ubuntu 18.04.1 and python 3.x,x in this machine. I clone the project but I the project wont execute by the above code. No UI is displayed.

**Comment by KenMacD** [comment]
I think you might have the project/fork. Maybe you're looking for https://github.com/electronicsguy/wdpassport-utils or https://github.com/0-duke/wdpassport-utils?

**Comment by ShanChathusanda93** [comment]
I tried. But the problem is the project is based on some early version of python before 3.x.x. but in my machine, I have 3.x.x. So, there is an invalid syntax error. But when I correct that error according to python 3.x.x there is no execution. This is the problem. Error is given below.

 ```
File "./wdpassport-utils.py", line 13
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
```

**Comment by KenMacD** [comment]
Hi @ShanChathusanda93. I'm sorry you're having issues, but unfortunately this isn't the place to report it as it's not an issue with code in this project. You could try to run it with `python2`, but really that's all I can suggest. If that project doesn't work for you feel free to try this one.

**Comment by ShanChathusanda93** [comment]
Hi @KenMacD. Could you please tell me where I want to report this issue?

**Comment by KenMacD** [comment]
@ShanChathusanda93 I'd suggest trying to find where that code is from and see if they have a mechanism to report it there.
